# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed78a19a7bf3c02bbe57ae1ab46c512794555c9cea527c4026179b2c9fef95f995700b1abe2bbdc73b17803b5788dad3b78dadc736c1f71830a875e5e2370286

test:
  secret_key_base: a36307c33460e69e7c7e656da7db85193032b707e88601d1514c048b9999c6b2de2c4ad512961584033ec807228ce4fc6bf4d22ed320baed3717ac972646d8ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
